openapi: 3.0.3
info:
  title: News API Service
  version: 1.0.0
  description: A wrapper around the GNews API to fetch news articles based on certain parameters.
servers:
  - url: 'http://localhost:3000'
paths:
  /articles:
    get:
      summary: Fetch news articles
      description: Fetch news articles based on the provided query parameters.
      parameters:
        - in: query
          name: amount
          schema:
            type: integer
            default: 10
          description: The number of articles to fetch.
        - in: query
          name: keyword
          schema:
            type: string
          description: Search for articles containing the specified keyword.
        - in: query
          name: title
          schema:
            type: string
          description: Search for articles with a title containing the specified string.
        - in: query
          name: author
          schema:
            type: string
          description: Search for articles authored by the specified author.
      responses:
        '200':
          description: A JSON array of articles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      description: The title of the article.
                    description:
                      type: string
                      description: A brief description of the article.
                    content:
                      type: string
                      description: The content of the article.
                    url:
                      type: string
                      description: The URL of the article.
                    image:
                      type: string
                      description: The URL of the article's main image.
                    publishedAt:
                      type: string
                      description: The date and time when the article was published, in ISO 8601 format.
                    source:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the source of the article.
                        url:
                          type: string
                          description: The URL of the source of the article.
